apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmapp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: app

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: {{ .Values.dbservice.port }}
      targetPort: {{ .Values.dbservice.port }}
      protocol: TCP
  selector:
    app: mongodb
